### ISSUE TITLE
응원합니다!

### ISSUE THREAD

**Issue by nupamore** [JJoriping/Sorrygle#1]
저는 6년 전에 비슷한 고민으로 작업한 프로젝트가 있습니다.
http://nupamore.github.io/Markdown-Music-Notation/examples/

코딩에 대해 잘 알지 못 하던 시절 아이디어만으로 만들고 버려졌는데, 이렇게 MIDI export까지 출력하는 프로젝트를 보니 너무 반갑네요.
제가 생각했던 다른 아이디어 중에 최근에 emoji가 보편적으로 사용되니 그걸 문법으로 사용해도 좋을 것 같다는 생각을 했었어요.
(p=🎻) 를 41번으로 치환해주던가 하면 재밌을 것 같습니다.

혹시 제 아이디어들에서 영감을 받아 도움이 된다면 기쁠 것 같아 글 남겨요.
MMD를 사용하는 새로운 게임이 개발중이라면, 소리글을 지원하길 바래봅니다.

**Comment by roeniss** [comment]
이모지 아이디어 너무 재밌네요! ㅎㅎ

**Comment by JJoriping** [comment]
헉 이모지를 쓸 생각을 못하고 악기 번호를 다 외워야되나... 했는데 그런 방법이 있었군요.
제안해 주신 내용은 1.1.0 패치에서 반영되었습니다.

좋은 의견 내주셔서 감사드립니다! ☺
