### ISSUE TITLE
When using multiple channels including drums, drum part does not sync well with the other parts

### ISSUE THREAD

**Issue by kitt3n69420** [JJoriping/Sorrygle#15]
(Sorry for bad English)
When playing/converting Sorrygle files that have both non-drum and drum parts, there are delays and inconsistencies on drum parts. And delay between drum and non-drum parts increases as song plays.
![image](https://github.com/JJoriping/Sorrygle/assets/100076733/8eb8ffc5-d13a-4b20-844a-f1fb681cbfdb)
the picture above is piano roll of midi file that I downloaded from Sorrygle web demo.
Drum notes(gray) are uneven, and kick/snare notes are out of sync with bass notes(dark red and orange).
This de-syncing happens when playing Sorrygle files on web demo or song list site, converting Sorrygle files to midi or mp3, and using Sorrygle bot.
The midi file was converted from this Sorrygle file:
```
((bpm=150))
#1(q=8)(o=3)(p=81)
|:[eg^c]~~~~~[eg^c][fa^c]~~~~~~~~[fG^c]~~~~[fG^c]~[eg^c]~~~~~~~~:|
(o=4)[vgce]~~~~~[vge][cfa]~~~~~~~~[cfG]~~~~[fG^c]~[eg^c]~~~~~~~~[eg^c]~~~~~[eg^c][fa^c]~~~~~~~~[fG^d][fG^d][fG^d]~~[fG^d]~[eg^c]________
#2(q=8)(o=2)(p=33)
{{basspatt1}}{
xxxxxxxx
}
{{basspatt1}}(cvfvGccvfvGccvfvGccvf)(vGGG~~G~)c________
#3(q=8)(o=3)(p=80)
|:c^cc^cc^cc^c:|13ccc__c_c_________
#4(q=4)(o=6)(p=80) c~~(:cc)~~~~c~(:_c_c)~~~~c~~(:cc)~~~~c~(:_c_c)~~~~c~~(:cc)~~~~c~(^(:_c_c)~~~~c~~(:cc)~~~~(:ddd__d_c)____)
#10(q=8)(o=2)(p=1)
  |:(:[cF]FFF):|27|:(:[cdF]FFF):|3 |: (:[cF]FFF[cdF]FFF):|11
 [[ 
[cd][cd][cd]~F[cd]F[cd]~~~~~~~~|
^C~~(q=16)b+b(q=8)a~~~__(q=16)(^cccc)bbbbaaaa(q=8)
]]
```

**Comment by JJoriping** [comment]
Fixed :) Thanks for the bug report
