### ISSUE TITLE
Ranged octave up 안에 Prima volta 가 포함 불가 오류

### ISSUE THREAD

**Issue by molla11** [JJoriping/Sorrygle#3]
```
|:
    (^ defed 
    /1 defed )
:|  /2 (^cdefgab^c~~~)
```
와 같이 `Ranged octave up(^ )` 안에 `Prima volta(/1)`가 포함될 경우, 프로그램이 오류를 발생시킵니다.

**Comment by JJoriping** [comment]
언어 구조상 Ranged octave up 안에 들어갈 수 있는 토큰은 아래와 같습니다:
- Local configuration
- Emoji reference
- Range
- Notation
- Group
- Parallelization
- 쉼표
- 공백

Prima volta는 Repetition 토큰(도돌이표 등이 이 토큰에 해당)이라 Ranged octave up에 넣을 수 없는 점 참고해 주시기 바라며... 아래와 같이 풀어서 나타내 주세요.
```
|:
       (^defed)
    /1 (^defed)
:|  /2 (^cdefgab^c~~~)
```
