### ISSUE TITLE
Arpeggio와 Sustain pedal 병용 시 박자 오류 현상

### ISSUE THREAD

**Issue by bennyk0406** [JJoriping/Sorrygle#5]
[우영우 오프닝.txt](https://github.com/JJoriping/Sorrygle/files/9314789/default.txt)

Line 36의 (s=127), Line 48의 (s=0)이 존재할 때와 존재하지 않을 때에 박자의 차이가 발생합니다.

**Comment by JJoriping** [comment]
아래와 같이 아르페지오 뒤에 붙임줄이 들어오는 경우 후속 음표(예에서 `^c`)가 붙임줄을 무시한 위치에 찍히는 문제로, 버전 1.3.1-a에서 대응했습니다.
```
#1       [|ceg]~~~^c~~~
#2 (o=3) vg_vg_   c_c_
```
